# GST CONFIG

GST_METADATA_DB_URI = 'mysql://root:guanshantech@106.15.35.240/test_superset'
GST_DEFAULT_DBS = {
    'gst-test-db': 'mysql://root:guanshantech@106.15.35.240/dwiformmaster',
    'gst-test-db2': 'mysql://root:guanshantech@106.15.35.240/dbiformmaster',
}
GST_DEFAULT_TABLES = [
    'gst-test-db.address',
    'gst-test-db.answer',
    'gst-test-db2.chart',
    'gst-test-db2.company',
]
GST_ROLE_VIEW_MENUS = {
    "MyIndexView",
    "UtilView",
    "LocaleView",
    "SecurityApi",
    "ResetPasswordView",
    "ResetMyPasswordView",
    "UserInfoEditView",
    "AuthDBView",
    "UserDBModelView",
    "RoleModelView",
    "UserStatsChartView",
    "PermissionModelView",
    "ViewMenuModelView",
    "PermissionViewModelView",
    "OpenApi",
    "Api",
    "TableColumnInlineView",
    "SqlMetricInlineView",
    "TableModelView",
    "DatabaseAsync",
    "DatabaseView",
    "CsvToDatabaseView",
    "DatabaseTablesAsync",
    "SliceModelView",
    "SliceAsync",
    "SliceAddView",
    "DashboardModelView",
    "DashboardModelViewAsync",
    "DashboardAddView",
    "KV",
    "R",
    "Superset",
    "CssTemplateModelView",
    "CssTemplateAsyncModelView",
    "QueryView",
    "SavedQueryViewApi",
    "SavedQueryView",
    "SqlLab",
    "Dashboard",
    "AnnotationLayerModelView",
    "AnnotationModelView",
    "Datasource",
    "TagView",
    "LogModelView",
    "DruidColumnInlineView",
    "DruidMetricInlineView",
    "DruidClusterModelView",
    "DruidDatasourceModelView",
    "Druid",
    # "Security",
    # "List Users",
    # "List Roles",
    # "User's Statistics",
    # "Base Permissions",
    # "Views/Menus",
    # "Permission on Views/Menus",
    # "Action Log",
    "Sources",
    "Tables",
    "Databases",
    # "Upload a CSV",
    # "Druid Clusters",
    # "Druid Datasources",
    # "Scan New Datasources",
    # "Refresh Druid Metadata",
    # "Manage",
    # "Import Dashboards",
    # "CSS Templates",
    # "Queries",
    # "Annotation Layers",
    # "Annotations",
    "Charts",
    "Dashboards",
    # "SQL Lab",
    # "SQL Editor",
    # "Query Search",
    # "Saved Queries",
    "all_datasource_access",
    "all_database_access",
    "can_only_access_owned_queries",
}
GST_ROLE_PERMISSIONS = {
    "all_database_access",
    "all_datasource_access",
    "can_add",
    "can_add_slices",
    "can_annotation_json",
    "can_approve",
    "can_available_domains",
    "can_cache_key_exist",
    "can_cached_key",
    "can_chart",
    "can_checkbox",
    "can_copy_dash",
    "can_created_dashboards",
    "can_created_slices",
    "can_csrf_token",
    "can_csv",
    "can_dashboard",
    "can_datasources",
    "can_delete",
    "can_download",
    "can_download_dashboards",
    "can_edit",
    "can_explore",
    "can_explore_json",
    "can_explorev2",
    "can_external_metadata",
    "can_extra_table_metadata",
    "can_fave_dashboards",
    "can_fave_dashboards_by_username",
    "can_fave_slices",
    "can_favstar",
    "can_fetch_datasource_metadata",
    "can_filter",
    "can_get",
    "can_get_value",
    "can_import_dashboards",
    "can_list",
    "can_my_queries",
    "can_new",
    "can_only_access_owned_queries",
    "can_override_role_permissions",
    "can_post",
    "can_profile",
    "can_publish",
    "can_queries",
    "can_query",
    "can_query_form_data",
    "can_recent_activity",
    "can_refresh_datasources",
    "can_request_access",
    "can_results",
    "can_save",
    "can_save_dash",
    "can_scan_new_datasources",
    "can_schemas",
    "can_schemas_access_for_csv_upload",
    "can_search_queries",
    "can_select_star",
    "can_shortner",
    "can_show",
    "can_slice",
    "can_slice_json",
    "can_slice_query",
    "can_sql_json",
    "can_sqllab",
    "can_sqllab_viz",
    "can_stop_query",
    "can_store",
    "can_suggestions",
    "can_sync_druid_source",
    "can_table",
    "can_tables",
    "can_tagged_objects",
    "can_testconn",
    "can_this_form_get",
    "can_this_form_post",
    "can_user_slices",
    "can_userinfo",
    "can_validate_sql_json",
    "can_warm_up_cache",
    "copyrole",
    "database_access",
    "datasource_access",
    "menu_access",
    "muldelete",
    "mulexport",
    "refresh",
    "resetmypassword",
    "resetpasswords",
    "userinfoedit",
    "yaml_export",
}

